name: fuba_clicker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  flutter_gen: ^5.12.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
 
  shared_preferences: ^2.3.3
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/song/
    # - assets/fonts/
