enum AchievementCategory {
  production,
  clicks,
  generators,
  accessories,
  lootBoxes,
  rebirth,
  secret,
}

enum AchievementDifficulty {
  common,
  uncommon,
  rare,
  epic,
  legendary,
}

enum AchievementRewardType {
  multiplier,
  tokens,
  unlockSecret,
}

class AchievementReward {
  final AchievementRewardType type;
  final double value;
  final String? secretId;

  const AchievementReward({
    required this.type,
    required this.value,
    this.secretId,
  });
}

class Achievement {
  final String id;
  final String name;
  final String emoji;
  final String description;
  final AchievementCategory category;
  final AchievementDifficulty difficulty;
  final bool isSecret;
  final double targetValue;
  final AchievementReward reward;

  const Achievement({
    required this.id,
    required this.name,
    required this.emoji,
    required this.description,
    required this.category,
    required this.difficulty,
    required this.targetValue,
    required this.reward,
    this.isSecret = false,
  });
}

const List<Achievement> allAchievements = [
  // Achievement(
  //   id: 'first_click',
  //   name: 'Primeiro Clique',
  //   emoji: '👆',
  //   description: 'Clique no bolo pela primeira vez',
  //   category: AchievementCategory.clicks,
  //   difficulty: AchievementDifficulty.common,
  //   targetValue: 1,
  //   reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  // ),
  Achievement(
    id: 'click_100',
    name: 'Clicador Dedicado',
    emoji: '💪',
    description: 'Clique no bolo 100 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_1000',
    name: 'Clicador Insano',
    emoji: '🔥',
    description: 'Clique no bolo 1000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_10000',
    name: 'Clicador Obsessivo',
    emoji: '💀',
    description: 'Clique no bolo 10.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'click_50000',
    name: 'Clicador Viciado',
    emoji: '🤯',
    description: 'Clique no bolo 50.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 50000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'click_100000',
    name: 'Clicador Lendário',
    emoji: '⚡',
    description: 'Clique no bolo 100.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'click_500000',
    name: 'Clicador Épico',
    emoji: '🌟',
    description: 'Clique no bolo 500.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 500000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.35),
  ),
  Achievement(
    id: 'click_1000000',
    name: 'Clicador Milionário',
    emoji: '💎',
    description: 'Clique no bolo 1 milhão de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.4),
  ),
  Achievement(
    id: 'click_10000000',
    name: 'Clicador Cósmico',
    emoji: '🌌',
    description: 'Clique no bolo 10 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.45),
  ),
  Achievement(
    id: 'click_50000000',
    name: 'Clicador Divino',
    emoji: '👑',
    description: 'Clique no bolo 50 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.5),
  ),
  Achievement(
    id: 'click_100000000',
    name: 'Clicador Supremo',
    emoji: '🔥',
    description: 'Clique no bolo 100 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.6),
  ),
  Achievement(
    id: 'click_500000000',
    name: 'Clicador Infinito',
    emoji: '♾️',
    description: 'Clique no bolo 500 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 500000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.7),
  ),
  Achievement(
    id: 'click_1000000000',
    name: 'Clicador Absoluto',
    emoji: '💀',
    description: 'Clique no bolo 1 bilhão de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.8),
  ),
  Achievement(
    id: 'production_1k',
    name: 'Produtor Iniciante',
    emoji: '🌽',
    description: 'Produza 1.000 fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'production_1m',
    name: 'Produtor Experiente',
    emoji: '🏭',
    description: 'Produza 1 milhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1e6,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'production_1b',
    name: 'Produtor Lendário',
    emoji: '👑',
    description: 'Produza 1 bilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1e9,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'production_1t',
    name: 'Produtor Cósmico',
    emoji: '🌌',
    description: 'Produza 1 trilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1e12,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'first_generator',
    name: 'Primeiro Gerador',
    emoji: '⚙️',
    description: 'Compre seu primeiro gerador',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.common,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'generator_10',
    name: 'Colecionador',
    emoji: '📦',
    description: 'Possua 10 geradores diferentes',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'generator_all',
    name: 'Mestre dos Geradores',
    emoji: '🎯',
    description: 'Possua todos os geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 30,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 1.0,
      secretId: 'cake_awakened',
    ),
  ),
  Achievement(
    id: 'first_accessory',
    name: 'Primeira Decoração',
    emoji: '✨',
    description: 'Consiga seu primeiro acessório',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.common,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'accessory_legendary',
    name: 'Sortudo',
    emoji: '💎',
    description: 'Consiga um acessório lendário',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'accessory_mythical',
    name: 'Abençoado pelos Deuses',
    emoji: '🌟',
    description: 'Consiga um acessório mítico',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'equip_8',
    name: 'Bolo Completo',
    emoji: '🎂',
    description: 'Equipe 8 acessórios ao mesmo tempo',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.rare,
    targetValue: 8,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'lootbox_10',
    name: 'Apostador',
    emoji: '🎰',
    description: 'Abra 10 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'lootbox_100',
    name: 'Viciado em Caixas',
    emoji: '📦',
    description: 'Abra 100 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'first_rebirth',
    name: 'Renascido',
    emoji: '🔄',
    description: 'Faça seu primeiro rebirth',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'rebirth_10',
    name: 'Ciclo Eterno',
    emoji: '♾️',
    description: 'Faça 10 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.epic,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'first_ascension',
    name: 'Ascendido',
    emoji: '✨',
    description: 'Faça sua primeira ascensão',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'first_transcendence',
    name: 'Transcendente',
    emoji: '🌟',
    description: 'Faça sua primeira transcendência',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 10),
  ),
  Achievement(
    id: 'click_speed_5',
    name: 'Velocista',
    emoji: '🏃',
    description: 'Alcance 5 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'click_speed_10',
    name: 'Relâmpago',
    emoji: '⚡',
    description: 'Alcance 10 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_speed_20',
    name: 'Turbina Humana',
    emoji: '🌪️',
    description: 'Alcance 20 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 20,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_speed_50',
    name: 'Máquina de Clicar',
    emoji: '🤖',
    description: 'Alcance 50 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'click_streak_100',
    name: 'Sequência Perfeita',
    emoji: '🎯',
    description: 'Faça 100 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_streak_500',
    name: 'Mestre da Sequência',
    emoji: '🔥',
    description: 'Faça 500 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 500,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_streak_1000',
    name: 'Lenda Viva',
    emoji: '👑',
    description: 'Faça 1000 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'fuba_per_click_100',
    name: 'Eficiência Máxima',
    emoji: '💎',
    description: 'Ganhe 100 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'fuba_per_click_1000',
    name: 'Multiplicador Divino',
    emoji: '✨',
    description: 'Ganhe 1000 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'fuba_per_click_10000',
    name: 'Poder Infinito',
    emoji: '🌟',
    description: 'Ganhe 10.000 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'secret_fast_clicker',
    name: '???',
    emoji: '⚡',
    description: 'Clique 50 vezes em 10 segundos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'secret_patience',
    name: '???',
    emoji: '⏰',
    description: 'Espere 1 hora sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 3600,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'secret_all_mythical',
    name: '???',
    emoji: '🎭',
    description: 'Equipe apenas acessórios míticos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 3,
    isSecret: true,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 2.0,
      secretId: 'divine_baker',
    ),
  ),
  Achievement(
    id: 'secret_no_generators',
    name: '???',
    emoji: '🚫',
    description: 'Alcance 100k fubá apenas clicando',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100000,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 10),
  ),
  Achievement(
    id: 'secret_midnight_clicker',
    name: '???',
    emoji: '🌙',
    description: 'Clique no bolo entre 00:00 e 01:00',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'secret_hoarder',
    name: '???',
    emoji: '🏺',
    description: 'Tenha 1000 acessórios no inventário',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 15),
  ),
  Achievement(
    id: 'secret_perfectionist',
    name: '???',
    emoji: '💎',
    description: 'Tenha exatamente 10 de cada gerador',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'secret_speed_demon',
    name: '???',
    emoji: '🏎️',
    description: 'Alcance 100 cliques por segundo',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'secret_time_traveler',
    name: '???',
    emoji: '⏰',
    description: 'Jogue por 24 horas consecutivas',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 86400,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 25),
  ),
  Achievement(
    id: 'secret_rainbow_collector',
    name: '???',
    emoji: '🌈',
    description: 'Equipe acessórios de todas as raridades',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 8,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.12),
  ),
  Achievement(
    id: 'secret_minimalist',
    name: '???',
    emoji: '🎯',
    description: 'Tenha exatamente 1 de cada gerador',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 30,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.08),
  ),
  Achievement(
    id: 'secret_lucky_streak',
    name: '???',
    emoji: '🍀',
    description: 'Abra 10 caixas lendárias seguidas',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'secret_zen_master',
    name: '???',
    emoji: '🧘',
    description: 'Produza 1 milhão de fubá sem clicar por 30 minutos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1800,
    isSecret: true,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.18),
  ),
  Achievement(
    id: 'secret_rebirth_master',
    name: '???',
    emoji: '♻️',
    description: 'Faça 100 rebirths',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100,
    isSecret: true,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 1.0,
      secretId: 'eternal_clicker',
    ),
  ),
];

