enum AchievementCategory {
  production,
  clicks,
  generators,
  accessories,
  lootBoxes,
  rebirth,
  secret,
}

enum AchievementDifficulty {
  common,
  uncommon,
  rare,
  epic,
  legendary,
}

enum AchievementRewardType {
  multiplier,
  tokens,
  unlockSecret,
}

class AchievementReward {
  final AchievementRewardType type;
  final double value;
  final String? secretId;

  const AchievementReward({
    required this.type,
    required this.value,
    this.secretId,
  });
}

class Achievement {
  final String id;
  final String name;
  final String emoji;
  final String description;
  final AchievementCategory category;
  final AchievementDifficulty difficulty;
  final double targetValue;
  final AchievementReward reward;

  const Achievement({
    required this.id,
    required this.name,
    required this.emoji,
    required this.description,
    required this.category,
    required this.difficulty,
    required this.targetValue,
    required this.reward,
  });
}

const List<Achievement> allAchievements = [
  // Achievement(
  //   id: 'first_click',
  //   name: 'Primeiro Clique',
  //   emoji: '👆',
  //   description: 'Clique no bolo pela primeira vez',
  //   category: AchievementCategory.clicks,
  //   difficulty: AchievementDifficulty.common,
  //   targetValue: 1,
  //   reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  // ),
  Achievement(
    id: 'click_100',
    name: 'Clicador Dedicado',
    emoji: '💪',
    description: 'Clique no bolo 100 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_1000',
    name: 'Clicador Insano',
    emoji: '🔥',
    description: 'Clique no bolo 1000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_10000',
    name: 'Clicador Obsessivo',
    emoji: '💀',
    description: 'Clique no bolo 10.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'click_50000',
    name: 'Clicador Viciado',
    emoji: '🤯',
    description: 'Clique no bolo 50.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 50000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'click_100000',
    name: 'Clicador Lendário',
    emoji: '⚡',
    description: 'Clique no bolo 100.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'click_500000',
    name: 'Clicador Épico',
    emoji: '🌟',
    description: 'Clique no bolo 500.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 500000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.35),
  ),
  Achievement(
    id: 'click_1000000',
    name: 'Clicador Milionário',
    emoji: '💎',
    description: 'Clique no bolo 1 milhão de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.4),
  ),
  Achievement(
    id: 'click_10000000',
    name: 'Clicador Cósmico',
    emoji: '🌌',
    description: 'Clique no bolo 10 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.45),
  ),
  Achievement(
    id: 'click_50000000',
    name: 'Clicador Divino',
    emoji: '👑',
    description: 'Clique no bolo 50 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.5),
  ),
  Achievement(
    id: 'click_100000000',
    name: 'Clicador Supremo',
    emoji: '🔥',
    description: 'Clique no bolo 100 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.6),
  ),
  Achievement(
    id: 'click_500000000',
    name: 'Clicador Infinito',
    emoji: '♾️',
    description: 'Clique no bolo 500 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 500000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.7),
  ),
  Achievement(
    id: 'click_1000000000',
    name: 'Clicador Absoluto',
    emoji: '💀',
    description: 'Clique no bolo 1 bilhão de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000000000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.8),
  ),
  Achievement(
    id: 'click_1000_daily',
    name: 'Clicador Iniciante',
    emoji: '👆',
    description: 'Clique 1000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.common,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'click_10000_daily',
    name: 'Clicador Ativo',
    emoji: '💪',
    description: 'Clique 10.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'click_100000_daily',
    name: 'Clicador Dedicado',
    emoji: '🔥',
    description: 'Clique 100.000 vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'click_1000000_daily',
    name: 'Clicador Obsessivo',
    emoji: '⚡',
    description: 'Clique 1 milhão de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'click_10000000_daily',
    name: 'Clicador Lendário',
    emoji: '🌟',
    description: 'Clique 10 milhões de vezes',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 15),
  ),
  Achievement(
    id: 'production_1k',
    name: 'Produtor Iniciante',
    emoji: '🌽',
    description: 'Produza 1.000 fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'production_1m',
    name: 'Produtor Experiente',
    emoji: '🏭',
    description: 'Produza 1 milhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1e6,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'production_1b',
    name: 'Produtor Lendário',
    emoji: '👑',
    description: 'Produza 1 bilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1e9,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'production_1t',
    name: 'Produtor Cósmico',
    emoji: '🌌',
    description: 'Produza 1 trilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1e12,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'production_1e500',
    name: 'Produtor Transcendente',
    emoji: '✨',
    description: 'Produza 1e500 fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1e500,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'production_1e1000',
    name: 'Produtor Eterno',
    emoji: '♾️',
    description: 'Produza 1e1000 fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1e1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.4),
  ),
  Achievement(
    id: 'production_1e1500',
    name: 'Produtor Absoluto',
    emoji: '👑',
    description: 'Produza 1e1500 fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1e1500,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.5),
  ),
  Achievement(
    id: 'production_1b_daily',
    name: 'Bilionário',
    emoji: '💰',
    description: 'Produza 1 bilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.common,
    targetValue: 1e9,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'production_1t_daily',
    name: 'Trilionário',
    emoji: '💎',
    description: 'Produza 1 trilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 1e12,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'production_1q_daily',
    name: 'Quatrilionário',
    emoji: '🏆',
    description: 'Produza 1 quatrilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1e15,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'production_1qi_daily',
    name: 'Quintilionário',
    emoji: '🌟',
    description: 'Produza 1 quintilhão de fubá total',
    category: AchievementCategory.production,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1e18,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'first_generator',
    name: 'Primeiro Gerador',
    emoji: '⚙️',
    description: 'Compre seu primeiro gerador',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.common,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'generator_10',
    name: 'Colecionador',
    emoji: '📦',
    description: 'Possua 10 geradores diferentes',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'generator_all',
    name: 'Mestre dos Geradores',
    emoji: '🎯',
    description: 'Possua todos os geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 60,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 1.0,
      secretId: 'cake_awakened',
    ),
  ),
  Achievement(
    id: 'generator_5_daily',
    name: 'Produtor Iniciante',
    emoji: '🌅',
    description: 'Possua 5 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.common,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'generator_10_daily',
    name: 'Fazendeiro',
    emoji: '🌾',
    description: 'Possua 10 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'generator_15_daily',
    name: 'Industrial',
    emoji: '🏭',
    description: 'Possua 15 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.rare,
    targetValue: 15,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'generator_20_daily',
    name: 'Magnata',
    emoji: '💼',
    description: 'Possua 20 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.epic,
    targetValue: 20,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 4),
  ),
  Achievement(
    id: 'generator_25_daily',
    name: 'Império',
    emoji: '👑',
    description: 'Possua 25 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 25,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 8),
  ),
  Achievement(
    id: 'generator_30_daily',
    name: 'Domínio',
    emoji: '🌟',
    description: 'Possua 30 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 30,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'generator_40_daily',
    name: 'Transcendente',
    emoji: '✨',
    description: 'Possua 40 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 40,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 15),
  ),
  Achievement(
    id: 'generator_50_daily',
    name: 'Eterno',
    emoji: '♾️',
    description: 'Possua 50 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'generator_60_daily',
    name: 'Absoluto',
    emoji: '👑',
    description: 'Possua 60 geradores',
    category: AchievementCategory.generators,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 60,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'first_accessory',
    name: 'Primeira Decoração',
    emoji: '✨',
    description: 'Consiga seu primeiro acessório',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.common,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'accessory_legendary',
    name: 'Sortudo',
    emoji: '💎',
    description: 'Consiga um acessório lendário',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'accessory_mythical',
    name: 'Abençoado pelos Deuses',
    emoji: '🌟',
    description: 'Consiga um acessório mítico',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'equip_8',
    name: 'Bolo Completo',
    emoji: '🎂',
    description: 'Equipe 8 acessórios ao mesmo tempo',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.rare,
    targetValue: 8,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'accessory_10_daily',
    name: 'Colecionador',
    emoji: '✨',
    description: 'Tenha 10 acessórios',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.common,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'accessory_25_daily',
    name: 'Decorador',
    emoji: '🎨',
    description: 'Tenha 25 acessórios',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 25,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'accessory_50_daily',
    name: 'Estilista',
    emoji: '💎',
    description: 'Tenha 50 acessórios',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'accessory_100_daily',
    name: 'Museu',
    emoji: '🏛️',
    description: 'Tenha 100 acessórios',
    category: AchievementCategory.accessories,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'lootbox_10',
    name: 'Apostador',
    emoji: '🎰',
    description: 'Abra 10 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'lootbox_100_total',
    name: 'Viciado em Caixas',
    emoji: '📦',
    description: 'Abra 100 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'lootbox_5_daily',
    name: 'Apostador Iniciante',
    emoji: '🎰',
    description: 'Abra 5 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.common,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'lootbox_20_daily',
    name: 'Jogador',
    emoji: '🎲',
    description: 'Abra 20 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 20,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'lootbox_50_daily',
    name: 'Cassino',
    emoji: '🎯',
    description: 'Abra 50 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'lootbox_100_daily',
    name: 'Mestre das Caixas',
    emoji: '🏆',
    description: 'Abra 100 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'lootbox_500',
    name: 'Viciado em Apostas',
    emoji: '🎰',
    description: 'Abra 500 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 500,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'lootbox_1000_total',
    name: 'Cassino Master',
    emoji: '🎲',
    description: 'Abra 1.000 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'lootbox_5000',
    name: 'Rei das Caixas',
    emoji: '👑',
    description: 'Abra 5.000 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 5000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'lootbox_10000',
    name: 'Imperador das Apostas',
    emoji: '🌟',
    description: 'Abra 10.000 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'lootbox_50000',
    name: 'Deus das Caixas',
    emoji: '✨',
    description: 'Abra 50.000 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.4),
  ),
  Achievement(
    id: 'lootbox_100000',
    name: 'Cósmico das Apostas',
    emoji: '🌌',
    description: 'Abra 100.000 caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.5),
  ),
  Achievement(
    id: 'lootbox_basic_100',
    name: 'Colecionador Básico',
    emoji: '📦',
    description: 'Abra 100 caixas básicas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'lootbox_advanced_50',
    name: 'Avançado',
    emoji: '🎁',
    description: 'Abra 50 caixas avançadas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 10),
  ),
  Achievement(
    id: 'lootbox_premium_25',
    name: 'Premium',
    emoji: '✨',
    description: 'Abra 25 caixas premium',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 25,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 15),
  ),
  Achievement(
    id: 'lootbox_ultimate_10',
    name: 'Supremo',
    emoji: '👑',
    description: 'Abra 10 caixas supremas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_divine_5',
    name: 'Divino',
    emoji: '💎',
    description: 'Abra 5 caixas divinas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_transcendent_3',
    name: 'Transcendente',
    emoji: '🌟',
    description: 'Abra 3 caixas transcendentais',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 3,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_primordial_2',
    name: 'Primordial',
    emoji: '🌌',
    description: 'Abra 2 caixas primordiais',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 2,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_cosmic_1',
    name: 'Cósmico',
    emoji: '🌠',
    description: 'Abra 1 caixa cósmica',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_infinite_1',
    name: 'Infinito',
    emoji: '♾️',
    description: 'Abra 1 caixa infinita',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_reality_1',
    name: 'Realidade',
    emoji: '🔮',
    description: 'Abra 1 caixa da realidade',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_omniversal_1',
    name: 'Omniversal',
    emoji: '🌐',
    description: 'Abra 1 caixa omniversal',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_tek_1',
    name: 'Tek Master',
    emoji: '💻',
    description: 'Abra 1 caixa de Tek',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_absolute_1',
    name: 'Absoluto',
    emoji: '👑',
    description: 'Abra 1 caixa absoluta',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_bulk_5',
    name: 'Comprador em Lote',
    emoji: '📦',
    description: 'Abra 5 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'lootbox_bulk_10',
    name: 'Comprador Avançado',
    emoji: '🎁',
    description: 'Abra 10 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 10),
  ),
  Achievement(
    id: 'lootbox_bulk_30',
    name: 'Comprador Profissional',
    emoji: '✨',
    description: 'Abra 30 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 30,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_bulk_100',
    name: 'Comprador Épico',
    emoji: '👑',
    description: 'Abra 100 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_bulk_500',
    name: 'Comprador Lendário',
    emoji: '🌟',
    description: 'Abra 500 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 500,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_bulk_1000',
    name: 'Comprador Absoluto',
    emoji: '💎',
    description: 'Abra 1.000 caixas de uma vez',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_legendary_10',
    name: 'Caçador de Lendas',
    emoji: '💎',
    description: 'Consiga 10 acessórios lendários de caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'lootbox_mythical_5',
    name: 'Caçador de Mitos',
    emoji: '🌟',
    description: 'Consiga 5 acessórios míticos de caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'lootbox_primordial_3',
    name: 'Caçador Primordial',
    emoji: '🌌',
    description: 'Consiga 3 acessórios primordiais de caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 3,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'lootbox_cosmic_2',
    name: 'Caçador Cósmico',
    emoji: '🌠',
    description: 'Consiga 2 acessórios cósmicos de caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 2,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'lootbox_infinite_accessory_1',
    name: 'Caçador Infinito',
    emoji: '♾️',
    description: 'Consiga 1 acessório infinito de caixas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'lootbox_all_tiers',
    name: 'Mestre de Todos os Tiers',
    emoji: '🎯',
    description: 'Abra caixas de todos os tiers',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 13,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'lootbox_lucky_streak_5',
    name: 'Sequência da Sorte',
    emoji: '🍀',
    description: 'Abra 5 caixas lendárias seguidas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_lucky_streak_10',
    name: 'Sequência Épica',
    emoji: '🔥',
    description: 'Abra 10 caixas lendárias seguidas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_lucky_streak_20',
    name: 'Sequência Lendária',
    emoji: '⚡',
    description: 'Abra 20 caixas lendárias seguidas',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 20,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_daily_200',
    name: 'Viciado Diário',
    emoji: '🎰',
    description: 'Abra 200 caixas em um dia',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 200,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_daily_500',
    name: 'Maniaco das Caixas',
    emoji: '🎲',
    description: 'Abra 500 caixas em um dia',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 500,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_daily_1000',
    name: 'Deus das Apostas',
    emoji: '👑',
    description: 'Abra 1.000 caixas em um dia',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_weekly_1000',
    name: 'Semanal das Caixas',
    emoji: '📅',
    description: 'Abra 1.000 caixas em uma semana',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_weekly_5000',
    name: 'Semanal Épico',
    emoji: '🌟',
    description: 'Abra 5.000 caixas em uma semana',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 5000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_weekly_10000',
    name: 'Semanal Lendário',
    emoji: '✨',
    description: 'Abra 10.000 caixas em uma semana',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_monthly_10000',
    name: 'Mensal das Caixas',
    emoji: '🗓️',
    description: 'Abra 10.000 caixas em um mês',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.epic,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 12),
  ),
  Achievement(
    id: 'lootbox_monthly_50000',
    name: 'Mensal Épico',
    emoji: '🏆',
    description: 'Abra 50.000 caixas em um mês',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'lootbox_monthly_100000',
    name: 'Mensal Lendário',
    emoji: '👑',
    description: 'Abra 100.000 caixas em um mês',
    category: AchievementCategory.lootBoxes,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 20),
  ),
  Achievement(
    id: 'first_rebirth',
    name: 'Renascido',
    emoji: '🔄',
    description: 'Faça seu primeiro rebirth',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'rebirth_10',
    name: 'Ciclo Eterno',
    emoji: '♾️',
    description: 'Faça 10 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.epic,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'first_ascension',
    name: 'Ascendido',
    emoji: '✨',
    description: 'Faça sua primeira ascensão',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'first_transcendence',
    name: 'Transcendente',
    emoji: '🌟',
    description: 'Faça sua primeira transcendência',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'rebirth_5_daily',
    name: 'Renascido Múltiplo',
    emoji: '🔄',
    description: 'Faça 5 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.common,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 1),
  ),
  Achievement(
    id: 'rebirth_25_daily',
    name: 'Ciclo Eterno',
    emoji: '♻️',
    description: 'Faça 25 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 25,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 2),
  ),
  Achievement(
    id: 'rebirth_50_daily',
    name: 'Eterno',
    emoji: '♾️',
    description: 'Faça 50 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'rebirth_100_daily',
    name: 'Mestre do Renascimento',
    emoji: '👑',
    description: 'Faça 100 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'rebirth_250_daily',
    name: 'Lenda do Renascimento',
    emoji: '🌟',
    description: 'Faça 250 rebirths',
    category: AchievementCategory.rebirth,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 250,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 10),
  ),
  Achievement(
    id: 'click_speed_5',
    name: 'Velocista',
    emoji: '🏃',
    description: 'Alcance 5 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 5,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'click_speed_10',
    name: 'Relâmpago',
    emoji: '⚡',
    description: 'Alcance 10 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_speed_20',
    name: 'Turbina Humana',
    emoji: '🌪️',
    description: 'Alcance 20 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 20,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_speed_50',
    name: 'Máquina de Clicar',
    emoji: '🤖',
    description: 'Alcance 50 cliques por segundo',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'click_streak_100',
    name: 'Sequência Perfeita',
    emoji: '🎯',
    description: 'Faça 100 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'click_streak_500',
    name: 'Mestre da Sequência',
    emoji: '🔥',
    description: 'Faça 500 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 500,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'click_streak_1000',
    name: 'Lenda Viva',
    emoji: '👑',
    description: 'Faça 1000 cliques consecutivos',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'fuba_per_click_100',
    name: 'Eficiência Máxima',
    emoji: '💎',
    description: 'Ganhe 100 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.rare,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'fuba_per_click_1000',
    name: 'Multiplicador Divino',
    emoji: '✨',
    description: 'Ganhe 1000 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'fuba_per_click_10000',
    name: 'Poder Infinito',
    emoji: '🌟',
    description: 'Ganhe 10.000 fubá por clique',
    category: AchievementCategory.clicks,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.2),
  ),
  Achievement(
    id: 'secret_fast_clicker',
    name: 'Clicador Veloz',
    emoji: '⚡',
    description: 'Clique 50 vezes em 10 segundos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 50,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.1),
  ),
  Achievement(
    id: 'secret_patience',
    name: 'Paciente',
    emoji: '⏰',
    description: 'Espere 1 hora sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 3600,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'secret_all_mythical',
    name: 'Colecionador Mítico',
    emoji: '🎭',
    description: 'Equipe apenas acessórios míticos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 3,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 2.0,
      secretId: 'divine_baker',
    ),
  ),
  Achievement(
    id: 'secret_no_generators',
    name: 'Puro Clicador',
    emoji: '🚫',
    description: 'Alcance 100k fubá apenas clicando',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 100000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 3),
  ),
  Achievement(
    id: 'secret_midnight_clicker',
    name: 'Clicador Noturno',
    emoji: '🌙',
    description: 'Clique no bolo entre 00:00 e 01:00',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 1,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'secret_hoarder',
    name: 'Colecionador Obsessivo',
    emoji: '🏺',
    description: 'Tenha 1000 acessórios no inventário',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1000,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 4),
  ),
  Achievement(
    id: 'secret_perfectionist',
    name: 'Perfeccionista',
    emoji: '💎',
    description: 'Tenha exatamente 10 de cada gerador',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'secret_speed_demon',
    name: 'Demônio da Velocidade',
    emoji: '🏎️',
    description: 'Alcance 100 cliques por segundo',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'secret_time_traveler',
    name: 'Viajante do Tempo',
    emoji: '⏰',
    description: 'Jogue por 24 horas consecutivas',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 86400,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 5),
  ),
  Achievement(
    id: 'secret_rainbow_collector',
    name: 'Colecionador Arco-íris',
    emoji: '🌈',
    description: 'Equipe acessórios de todas as raridades',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 8,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.12),
  ),
  Achievement(
    id: 'secret_minimalist',
    name: 'Minimalista',
    emoji: '🎯',
    description: 'Tenha exatamente 1 de cada gerador',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 30,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.08),
  ),
  Achievement(
    id: 'secret_lucky_streak',
    name: 'Sequência da Sorte',
    emoji: '🍀',
    description: 'Abra 10 caixas lendárias seguidas',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 10,
    reward: AchievementReward(type: AchievementRewardType.tokens, value: 8),
  ),
  Achievement(
    id: 'secret_zen_master',
    name: 'Mestre Zen',
    emoji: '🧘',
    description: 'Produza 1 milhão de fubá sem clicar por 30 minutos',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1800,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.18),
  ),
  Achievement(
    id: 'secret_rebirth_master',
    name: 'Mestre do Renascimento',
    emoji: '♻️',
    description: 'Faça 100 rebirths',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 100,
    reward: AchievementReward(
      type: AchievementRewardType.unlockSecret,
      value: 1.0,
      secretId: 'eternal_clicker',
    ),
  ),
  Achievement(
    id: 'secret_meditation_30s',
    name: 'Meditação Rápida',
    emoji: '🧘‍♂️',
    description: 'Fique 30 segundos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.common,
    targetValue: 30,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.02),
  ),
  Achievement(
    id: 'secret_meditation_1m',
    name: 'Meditação Curta',
    emoji: '🧘',
    description: 'Fique 1 minuto sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 60,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.03),
  ),
  Achievement(
    id: 'secret_meditation_2m',
    name: 'Meditação Breve',
    emoji: '🕐',
    description: 'Fique 2 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.uncommon,
    targetValue: 120,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.04),
  ),
  Achievement(
    id: 'secret_meditation_5m',
    name: 'Meditação Moderada',
    emoji: '⏰',
    description: 'Fique 5 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 300,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.05),
  ),
  Achievement(
    id: 'secret_meditation_10m',
    name: 'Meditação Longa',
    emoji: '⏳',
    description: 'Fique 10 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 600,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.06),
  ),
  Achievement(
    id: 'secret_meditation_15m',
    name: 'Meditação Estendida',
    emoji: '🕒',
    description: 'Fique 15 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.rare,
    targetValue: 900,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.07),
  ),
  Achievement(
    id: 'secret_meditation_30m',
    name: 'Meditação Profunda',
    emoji: '🕕',
    description: 'Fique 30 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 1800,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.08),
  ),
  Achievement(
    id: 'secret_meditation_45m',
    name: 'Meditação Intensa',
    emoji: '🕕',
    description: 'Fique 45 minutos sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 2700,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.09),
  ),
  Achievement(
    id: 'secret_meditation_2h',
    name: 'Meditação Maratona',
    emoji: '🕗',
    description: 'Fique 2 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.epic,
    targetValue: 7200,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.12),
  ),
  Achievement(
    id: 'secret_meditation_4h',
    name: 'Meditação Épica',
    emoji: '🕙',
    description: 'Fique 4 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 14400,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.15),
  ),
  Achievement(
    id: 'secret_meditation_8h',
    name: 'Meditação Lendária',
    emoji: '🕛',
    description: 'Fique 8 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 28800,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.18),
  ),
  Achievement(
    id: 'secret_meditation_12h',
    name: 'Meditação Suprema',
    emoji: '🌅',
    description: 'Fique 12 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 43200,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.22),
  ),
  Achievement(
    id: 'secret_meditation_24h',
    name: 'Meditação Absoluta',
    emoji: '🌄',
    description: 'Fique 24 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 86400,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.25),
  ),
  Achievement(
    id: 'secret_meditation_48h',
    name: 'Meditação Divina',
    emoji: '🌅',
    description: 'Fique 48 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 172800,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.3),
  ),
  Achievement(
    id: 'secret_meditation_72h',
    name: 'Meditação Cósmica',
    emoji: '🌇',
    description: 'Fique 72 horas sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 259200,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.35),
  ),
  Achievement(
    id: 'secret_meditation_week',
    name: 'Meditação Eterna',
    emoji: '🗓️',
    description: 'Fique 1 semana sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 604800,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.4),
  ),
  Achievement(
    id: 'secret_meditation_month',
    name: 'Meditação Infinita',
    emoji: '📅',
    description: 'Fique 1 mês sem clicar',
    category: AchievementCategory.secret,
    difficulty: AchievementDifficulty.legendary,
    targetValue: 2592000,
    reward: AchievementReward(type: AchievementRewardType.multiplier, value: 1.5),
  ),
];

